site_name: 微风吹走云
site_author: aaaa
site_description: 站点描述aaaa
copyright: 版权信息TM

#开启按钮图标
markdown_extensions:
  - attr_list
  - md_in_html
#开启图片
plugins:
  - glightbox
#开启告诫
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
#主题
theme:
  features:
    - navigation.tabs
    - navigation.top
  language: zh 
  name: 'material'
  palette: 
  # Palette toggle for light mode
  - primary: teal
    toggle:
      icon: material/toggle-switch
      name: Switch to dark mode
  # Palette toggle for dark mode
  - scheme: slate
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to light mode
 
#导航
nav:
- Hi！你好: index.md
- 做点游戏:
  - DEMO: demo.md
  - 日志: log.md
- 程序:
    
- 生活: life.md
- 随便聊聊: talk.md

#插件
plugins:
    #搜索插件
    - search:
        separator: '[\s\-\.]+'
     #灯箱：可以打开图片   
    - glightbox:

#本地运行地址
dev_addr: 127.0.0.1:5500
#下部
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dreamskycx/waterbox
      name: 水箱档案馆开源
    - icon: fontawesome/brands/qq
      link: https://jq.qq.com/?_wv=1027&k=WrW83q3O
      name: 水箱游戏交流群（538229336）






      #python -m mkdocs serve